apiRules:
- include:
    # Including the OmiyaGames.Global.Settings namespace
    uidRegex: ^OmiyaGames\.Global\.Settings$
    type: Namespace
- include:
    # Including the OmiyaGames.Global.Settings.Editor namespace
    uidRegex: ^OmiyaGames\.Global\.Settings\.Editor$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    # Taro Omiya: note that I'm ignoring namespaces containing unit tests on purpooses
    uidRegex: .*
    type: Namespace
